/** Auto-generated by scripts/gen-hanout-images.ts — placeholder product tiles. */
export const HANOUT_IMAGES: Record<string, { w: number; h: number; blur: string }> = {
  "coffee-set": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQABAAA4BaJZgCdAEPAFNiF4cQAP72CqxUPH1WtYWWjNPLMPjHVqB3218fgk4MJOKf+zY6mW3bZ7uscPHA5iifd8hwTVfqSHN1EAAA"
  },
  "table-lamp": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAwAgCdASoQABAAA4BaJagCdAEPAm+t0r3QAAD+9gjf8J+9Dp35X7bpwWzmdGtCWMb72UF/iTJqOW/IzTW2102gAAA="
  },
  "cookware-set": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAQCdASoQABAAA4BaJaAAAudf/PMaaqAA/vYJqQo1y5KLj8jyC3hSXXO8yfVR/fz+PTyfVyqePxbQlnGf94BsYuoS1A2LPk3HOvH7vFz8gAAA"
  },
  "care-gift-box": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQABAAA4BaJQBOgCHgT0M5YAD+9gmpB+STcH6Lv2IMH3rkRQRY/bNxVnJkZAUVN6irRaudcynq8HV7AAA="
  },
  "perfume": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoQABAAA4BaJYwCdAEPAAM2+bDoAP72CqzdWi01jeYBZDs+H2UmC8J5VsjHIWr6tik3WxefUl1dNZxQf9o995D8AAA="
  },
  "moisturizer": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQABAAA4BaJYgAAudVgsk+fgAA/vYI34NdDtEZT3mmbGV/kZR0YDypTbvmwmn28jNbZuuqUTJ30vPnAGAAARgAAAA="
  },
  "wireless-earbuds": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAgCdASoQABAAA4BaJYwC7AEPAG2iGnCgAAD+9gmpB7sa1/gCVtlzUebbFkNFL/vp1qJgikWkazLMyDQcAigA"
  },
  "smartwatch": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABwAgCdASoQABAAA4BaJZQBTAFu07dogfcwKNcAAP72Et/sps9KnEu5vjsc1J3x2T7Rfz7PFhJPP++g3fAZ0fAnwW/Xtq9mHaNoxCSUxZctse62Whps2dw4AAA="
  },
  "power-bank": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQABAAA4BaJZgC7AEO+nmWTYAA/vYRF7lXCJffmqW2L9lYcP8AeHM2HUT+g6appPH5imsqbaI/PAAA"
  },
  "bluetooth-speaker": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQABAAA4BaJZAAAudegpugvdAA/vYJqQfk2lpErUBy3aV/0JJYNxk/wD+Y6G6u/sGz1ytZwLiIIzksosI5dQcUIsxqDp84AAA="
  },
  "leather-handbag": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQABAAA4BaJZgCdAEO/8boBvoAAP72EO8rvqYWjpVJTGWGzSQbGxTULNDNREprYu2EMlwY/4mmMtg7lYDCOhnw7NgAAA=="
  },
  "running-sneakers": {
    "w": 800,
    "h": 800,
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoQABAAA4BaJZQAAudQSXw/egAA/vYI34NcQWtg859BkWJsJa7ppkMSGTsAMMmf+/uh9vA5oq8ViOZMNgAAAA=="
  }
};
