/** Landing page copy — Arabic (default) and English. */
export const HOME = {
  ar: {
    metaTitle: "حانوت — كلّ واحد ودوره",
    metaDesc: "حانوت يرتّب طلباتك وفريقك: تأكيد الطلبات تلقائيًا، أقسام وأدوار، ومحادثة لكل قسم.",
    heroPre: "كلّ",
    heroMark: "واحد",
    heroPost: "ودوره",
    heroSub: "نظام يرتّب طلباتك وفريقك.. من أول طلب حتى التسليم.",
    ctaShop: "اطلب من المتجر كزبون",
    ctaTeam: "ادخل كأحد أفراد الفريق",
    qrTitle: "جرّبه من هاتفك",
    qrHint: "امسح واطلب، ثم شاهد الطلب يصل هنا",
    phoneBrand: "حانوت",
    phoneDept: "قسم التأكيد",
    phoneTitle: "طلب جديد",
    phoneEmpty: "في انتظار أول طلب…",
    phoneStatus: "قيد التأكيد",
    merchants: { title: "للتجار", line: "رابط تأكيد يعمل مع أي متجر", pill: "تأكيد الطلبات تلقائيًا", confirmedBy: "تم تأكيد الطلب بواسطة الزبون", yes: "نعم، أؤكد طلبي" },
    crafts: { title: "للحرفيين", line: "أقرب حرفي، طلب، ومحادثة", q: "هل يمكن إصلاح تسرّب الماء اليوم؟", a: "نعم، أصل بعد 30 دقيقة" },
    business: { title: "للشركات", line: "قالب جاهز لتنظيم فريقك", people: [["خالد", "مدير"], ["مريم", "استقبال"], ["يوسف", "تنفيذ"]] },
    mTitle1: "كل طلب يُؤكَّد",
    mTitle2: "قبل أن يُشحن",
    mBody: "أغلب الطلبات في الجزائر تُدفع عند الاستلام، والطلب غير المؤكَّد يرجع ويكلّفك. حانوت يرسل للزبون رابط تأكيد، ويضع كل طلب في قسمه: التأكيد، ثم التحضير، ثم الشحن — وكل خطوة تظهر في جروب القسم.",
    steps: [
      ["الزبون يطلب", "من متجرك على حانوت أو من أي متجر آخر عبر رابط التأكيد."],
      ["يؤكّد بنقرة", "أو يتصل به مؤكِّد من فريقك: لم يرد، مؤجل، رقم خاطئ — كل شيء مسجّل."],
      ["فريقك يحضّر ويشحن", "الطلب ينتقل وحده للقسم التالي، والزبون يتابعه لحظة بلحظة."],
    ],
    couriers: "شركات التوصيل في قسم الشحن",
    facts: [["58", "ولاية"], ["COD", "الدفع عند الاستلام"], ["AR · FR · EN", "صفحة التأكيد"]],
    tryShop: "جرّب: اطلب من متجر نور",
    soon: "قريبًا",
    cTitle: "للحرفيين",
    cBody: "الزبون يطلب أقرب حرفي، والورشة توزّع العمل على مساعديها — بنفس النظام.",
    cTags: ["سباكة", "كهرباء", "تكييف", "دهان", "نجارة", "تنظيف"],
    cJob: "طلب عمل جديد · تسرّب ماء",
    cKm: "2.3 كم",
    cWhere: "باب الزوار · اليوم 15:00",
    accept: "قبول",
    decline: "رفض",
    bTitle: "للشركات",
    bBody: "اختر قالبًا جاهزًا وحدّد الأقسام والأدوار: كل موظف يرى مهامه وجروب قسمه.",
    bTags: ["مقهى", "مركز تكوين", "وكالة", "ورشة"],
    bStages: ["جديد", "مؤكد", "قيد الإنجاز", "مكتمل"],
    leadTitle: "نرتّب لك فريقك؟",
    leadBody: "اترك رقمك ونتصل بك لنجهّز حانوت لمتجرك أو ورشتك أو شركتك.",
    whatsapp: "راسلنا على WhatsApp",
  },
  en: {
    metaTitle: "Hanout — Everyone has a role",
    metaDesc: "Hanout organizes your orders and your team: automatic order confirmation, departments and roles, and a chat for every department.",
    heroPre: "Everyone has a",
    heroMark: "role",
    heroPost: "",
    heroSub: "One system for your orders and your team — from the first order to delivery.",
    ctaShop: "Order as a customer",
    ctaTeam: "Join as a team member",
    qrTitle: "Try it on your phone",
    qrHint: "Scan, order, and watch it arrive here",
    phoneBrand: "Hanout",
    phoneDept: "Confirmation",
    phoneTitle: "New order",
    phoneEmpty: "Waiting for the first order…",
    phoneStatus: "To confirm",
    merchants: { title: "Merchants", line: "A confirmation link that works with any store", pill: "Automatic order confirmation", confirmedBy: "Confirmed by the customer", yes: "Yes, I confirm" },
    crafts: { title: "Artisans", line: "Nearest artisan, request, and chat", q: "Can you fix a water leak today?", a: "Yes, I'll be there in 30 minutes" },
    business: { title: "Business", line: "A ready template to organize your team", people: [["Khaled", "Manager"], ["Meriem", "Front desk"], ["Youcef", "Operations"]] },
    mTitle1: "Every order confirmed",
    mTitle2: "before it ships",
    mBody: "Most orders in Algeria are paid on delivery, and an unconfirmed order comes back and costs you. Hanout sends the customer a confirmation link and puts every order in its department: confirmation, then packing, then shipping — each step posted in the department's chat.",
    steps: [
      ["The customer orders", "From your Hanout store, or from any other store through the confirmation link."],
      ["Confirms in one tap", "Or a confirmer on your team calls: no answer, postponed, wrong number — all recorded."],
      ["Your team packs and ships", "The order moves to the next department on its own, and the customer follows it live."],
    ],
    couriers: "Delivery companies at shipping",
    facts: [["58", "wilayas"], ["COD", "cash on delivery"], ["AR · FR · EN", "confirmation page"]],
    tryShop: "Try it: order from Noor store",
    soon: "Coming soon",
    cTitle: "Artisans",
    cBody: "Customers request the nearest artisan, and the workshop assigns the job to its helpers — on the same system.",
    cTags: ["Plumbing", "Electrical", "AC", "Painting", "Carpentry", "Cleaning"],
    cJob: "New job · Water leak",
    cKm: "2.3 km",
    cWhere: "Bab Ezzouar · today 15:00",
    accept: "Accept",
    decline: "Decline",
    bTitle: "Business",
    bBody: "Pick a ready template and set departments and roles: every employee sees their tasks and their department's chat.",
    bTags: ["Café", "Training center", "Agency", "Workshop"],
    bStages: ["New", "Confirmed", "In progress", "Done"],
    leadTitle: "Let's organize your team",
    leadBody: "Leave your number and we'll call you to set up Hanout for your store, workshop or company.",
    whatsapp: "Message us on WhatsApp",
  },
} as const;
